name: ter-release
channels:
  - defaults
dependencies:
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.1
  - python=3.7.10
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - dill==0.3.3
    - filelock==3.0.12
    - gin==0.1.6
    - gin-config==0.4.0
    - gym==0.18.3
    - gym-minigrid==1.0.2
    - gym-sokoban==0.0.6
    - imageio==2.9.0
    - numpy==1.20.3
    - opencv-python==4.5.2.52
    - pfrl==0.2.1
    - pyglet==1.5.15
    - requests==2.25.1
    - scipy==1.6.3
    - torch==1.8.1
    - tqdm==4.61.0
    - urllib3==1.26.5
    - ruamel.yaml
